version: '3.9'

services:
  tor:
    image: domistyle/tor-browser
    restart: always
    ports:
      - 5800:5800
      - 5900:5900
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      KEEP_APP_RUNNING: 1
      TZ: Europe/Vienna
    volumes:
      - /srv/tor:/app/Browser/TorBrowser/Data/Tor
