name: Check for Tor Browser arm64 update

on:
  schedule:
    - cron:  '0 1 * * *'  # daily at 01:00 UTC
  workflow_dispatch:

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check if Tor Browser Ports has an arm64 build for the latest release
        run: |
          echo "TB_UPDATED=1" >> $GITHUB_ENV
          latest=$(awk -F '=' '/TOR_VERSION_X64/{print $NF; exit}' Dockerfile | tr -d '"')
          curl --fail -I -X GET https://sourceforge.net/projects/tor-browser-ports/files/$latest
          current=$(awk -F '=' '/TOR_VERSION_ARM64/{print $NF; exit}' Dockerfile | tr -d '"')
          dpkg --compare-versions $latest gt $current && update=0 || update=1
          echo "TB_UPDATED=$update" >> $GITHUB_ENV
          echo "TB_VERSION=$latest" >> $GITHUB_ENV
        continue-on-error: true
          
      - name: Update arm64 to latest version and commit update
        if: ${{ env.TB_UPDATED == 0 }}
        run: |
          sed -i s/TOR_VERSION_ARM64=".*"/TOR_VERSION_ARM64=\"${{ env.TB_VERSION }}\"/g Dockerfile
          git config --global user.name "github-runner[bot]"
          git config --global user.email "github-runner[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated Tor Browser arm64 version to ${{ env.TB_VERSION }} " || echo
          git push origin ${GITHUB_REF##*/} -f
